"""Response formatter that converts AI text and tool results into structured frontend messages."""

from __future__ import annotations

import json
from typing import Any

import structlog

from agent.formatters.message_types import (
    BookingConfirmedMessage,
    BudgetEstimateMessage,
    ComparisonMessage,
    ImageGalleryMessage,
    ItineraryMessage,
    QRPaymentMessage,
    TextMessage,
    TripCardsMessage,
    WeatherMessage,
)
from agent.session.state import AgentState, ConversationState

logger = structlog.get_logger(__name__)


def _parse_tool_data(tool_results: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Extract parsed data payloads from raw tool results."""
    parsed_items: list[dict[str, Any]] = []
    for result in tool_results:
        content = result.get("content", "")
        if isinstance(content, str):
            try:
                parsed = json.loads(content)
                parsed_items.append(parsed)
            except (json.JSONDecodeError, TypeError):
                pass
        elif isinstance(content, dict):
            parsed_items.append(content)
    return parsed_items


def _match_structured_data(
    ai_text: str,
    all_data: list[dict[str, Any]],
) -> dict[str, Any] | None:
    """Attempt to match tool data against known structured message patterns.

    Returns a serialized message dict if a pattern matches, otherwise ``None``.
    """
    for data in all_data:
        actual = data.get("data", data)

        # Trip suggestions / comparison
        trips = actual.get("trips")
        if isinstance(trips, list) and len(trips) > 0:
            if len(trips) == 2:
                return ComparisonMessage(content=ai_text, trips=trips).model_dump()
            return TripCardsMessage(content=ai_text, trips=trips).model_dump()

        # QR payment
        if "qr_code_url" in actual:
            return QRPaymentMessage(
                content=ai_text,
                qr_code_url=actual["qr_code_url"],
                amount=actual.get("amount"),
                currency=actual.get("currency"),
                booking_ref=actual.get("booking_ref"),
                expires_at=actual.get("expires_at"),
            ).model_dump()

        # Weather forecast
        if "forecast" in actual:
            return WeatherMessage(
                content=ai_text,
                forecast=actual["forecast"],
            ).model_dump()

        # Itinerary
        if "itinerary" in actual:
            return ItineraryMessage(
                content=ai_text,
                itinerary=actual["itinerary"],
            ).model_dump()

        # Budget estimate
        if "total_estimate_usd" in actual:
            return BudgetEstimateMessage(
                content=ai_text,
                total_estimate_usd=actual["total_estimate_usd"],
                breakdown=actual.get("breakdown"),
            ).model_dump()

        # Image gallery
        if "images" in actual and isinstance(actual["images"], list):
            return ImageGalleryMessage(
                content=ai_text,
                images=actual["images"],
            ).model_dump()

    return None


def format_response(
    ai_text: str,
    tool_results: list[dict[str, Any]],
    session: ConversationState,
) -> dict[str, Any]:
    """Analyze AI text and tool results to produce a structured frontend message.

    The function inspects tool result payloads for known data patterns (trips,
    QR codes, weather, itineraries, etc.) and wraps them in the appropriate
    Pydantic message model.  When no structured data is detected it falls back
    to a plain ``TextMessage``.

    Args:
        ai_text: The natural-language response generated by the LLM.
        tool_results: Raw tool-call result dicts produced during the agent turn.
        session: The current conversation state (used for booking-stage checks).

    Returns:
        A JSON-serializable dict ready to be sent over WebSocket to the frontend.
    """
    all_data = _parse_tool_data(tool_results)

    structured = _match_structured_data(ai_text, all_data)
    if structured is not None:
        logger.info(
            "formatted_structured_response",
            message_type=structured.get("type"),
            tool_result_count=len(tool_results),
        )
        return structured

    # Check for booking confirmed state
    if (
        session.state == AgentState.POST_BOOKING
        and session.payment_status == "CONFIRMED"
    ):
        logger.info(
            "formatted_booking_confirmed",
            booking_id=session.booking_id,
        )
        return BookingConfirmedMessage(
            content=ai_text,
            booking_id=session.booking_id,
            booking_ref=session.booking_ref,
        ).model_dump()

    # Default: plain text
    return TextMessage(content=ai_text).model_dump()
